@startuml

title __MODEL's Class Diagram__\n

  namespace com.team1.animalproject {
    namespace model {
      class com.team1.animalproject.model.Animal {
          + address : String
          + birthdate : Date
          + id : String
          + name : String
          + specie : String
          + type : String
          {static} - serialVersionUID : long
          + Animal()
          + Animal()
          {static} + builder()
          + equals()
          + getAddress()
          + getBirthdate()
          + getId()
          + getName()
          + getSpecie()
          + getType()
          + hashCode()
          + setAddress()
          + setBirthdate()
          + setId()
          + setName()
          + setSpecie()
          + setType()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.team1.animalproject {
    namespace model {
      class com.team1.animalproject.model.Animal.AnimalBuilder {
          - address : String
          - birthdate : Date
          - id : String
          - name : String
          - specie : String
          - type : String
          + address()
          + birthdate()
          + build()
          + id()
          + name()
          + specie()
          + toString()
          + type()
          ~ AnimalBuilder()
      }
    }
  }
  

  namespace com.team1.animalproject {
    namespace model {
      class com.team1.animalproject.model.Kullanici {
          + email : String
          + id : String
          + name : String
          + password : String
          + phoneNumber : String
          + surname : String
          + userName : String
          {static} - serialVersionUID : long
          + Kullanici()
          + Kullanici()
          {static} + builder()
          + equals()
          + getEmail()
          + getId()
          + getName()
          + getPassword()
          + getPhoneNumber()
          + getSurname()
          + getUserName()
          + hashCode()
          + setEmail()
          + setId()
          + setName()
          + setPassword()
          + setPhoneNumber()
          + setSurname()
          + setUserName()
          + toString()
          # canEqual()
      }
    }
  }
  

  namespace com.team1.animalproject {
    namespace model {
      class com.team1.animalproject.model.Kullanici.KullaniciBuilder {
          - email : String
          - id : String
          - name : String
          - password : String
          - phoneNumber : String
          - surname : String
          - userName : String
          + build()
          + email()
          + id()
          + name()
          + password()
          + phoneNumber()
          + surname()
          + toString()
          + userName()
          ~ KullaniciBuilder()
      }
    }
  }
  

  namespace com.team1.animalproject {
    namespace model {
      class com.team1.animalproject.model.Student {
          + city : String
          + distinct : String
          + image : Blob
          + phoneNumber : String
          + studentName : String
          + studentNumber : String
          + studentSurname : String
          {static} - serialVersionUID : long
          + Student()
          + Student()
          + getCity()
          + getDistinct()
          + getImage()
          + getPhoneNumber()
          + getStudentName()
          + getStudentNumber()
          + getStudentSurname()
          + setCity()
          + setDistinct()
          + setImage()
          + setPhoneNumber()
          + setStudentName()
          + setStudentNumber()
          + setStudentSurname()
          + toString()
      }
    }
  }
  

  com.team1.animalproject.model.Animal .up.|> java.io.Serializable
  com.team1.animalproject.model.Animal +-down- com.team1.animalproject.model.Animal.AnimalBuilder
  com.team1.animalproject.model.Kullanici .up.|> java.io.Serializable
  com.team1.animalproject.model.Kullanici +-down- com.team1.animalproject.model.Kullanici.KullaniciBuilder
  com.team1.animalproject.model.Student .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
