@startuml

title __SERVÝCE's Class Diagram__\n

  namespace com.team1.animalproject {
    namespace service {
      class com.team1.animalproject.service.AnimalService {
          + delete()
          + getAll()
          + save()
          + update()
      }
    }
  }
  

  namespace com.team1.animalproject {
    namespace service {
      interface com.team1.animalproject.service.IBaseService {
          {abstract} + delete()
          {abstract} + getAll()
          {abstract} + save()
          {abstract} + update()
      }
    }
  }
  

  namespace com.team1.animalproject {
    namespace service {
      interface com.team1.animalproject.service.IStudentService {
          {abstract} + deleteStudent()
          {abstract} + getAllStudent()
          {abstract} + saveStudent()
          {abstract} + updateStudent()
      }
    }
  }
  

  namespace com.team1.animalproject {
    namespace service {
      class com.team1.animalproject.service.StudentServiceImpl {
          {static} + city : String
          {static} + image : byte[]
          {static} - logger : Logger
          - savedStudents : List<Student>
          + StudentServiceImpl()
          + deleteStudent()
          + getAllStudent()
          + saveStudent()
          + updateStudent()
          - getRandomId()
      }
    }
  }
  

  namespace com.team1.animalproject {
    namespace service {
      class com.team1.animalproject.service.UserService {
          + delete()
          + findById()
          + findByUserNameAndPassword()
          + getAll()
          + save()
          + update()
      }
    }
  }
  

  com.team1.animalproject.service.AnimalService .up.|> com.team1.animalproject.service.IBaseService
  com.team1.animalproject.service.AnimalService o-- com.team1.animalproject.repository.AnimalRepository : animalRepository
  com.team1.animalproject.service.StudentServiceImpl .up.|> com.team1.animalproject.service.IStudentService
  com.team1.animalproject.service.StudentServiceImpl o-- com.team1.animalproject.repository.StudentRepository : studentRepository
  com.team1.animalproject.service.UserService .up.|> com.team1.animalproject.service.IBaseService
  com.team1.animalproject.service.UserService o-- com.team1.animalproject.repository.UserRepository : userRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
